version: '3.8'  

services:

  grpc-server:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - "50055:50053"
    env_file: 
      - ./envs/local.env
    depends_on:
      - db
    links: 
      - db

  envoy-proxy: 
    image: envoyproxy/envoy:v1.25-latest # Envoy proxy image version 
    volumes: 
      - ./envoy.yaml:/etc/envoy/envoy.yaml # Mounting envoy.yaml file to the container 
    ports: 
      - "8081:8081"
      - "9902:8002"
    # depends_on: 
    #   - grpc-server 
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
  
  db: 
    image: postgres:alpine
    restart: always 
    environment: 
      - POSTGRES_PASSWORD=pGdBcrM
      - POSTGRES_DB=pipelines-db-1
      - POSTGRES_USER=root
    ports: 
      - "5432:5432"
    volumes: 
      - data:/var/lib/postgresql/data
volumes:
  data: 