// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pkg/proto/pipelines.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pipelines struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pipelines) Reset() {
	*x = Pipelines{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_pipelines_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pipelines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipelines) ProtoMessage() {}

func (x *Pipelines) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pipelines_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipelines.ProtoReflect.Descriptor instead.
func (*Pipelines) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pipelines_proto_rawDescGZIP(), []int{0}
}

type GetPipelinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganisationId string `protobuf:"bytes,1,opt,name=organisationId,proto3" json:"organisationId,omitempty"`
}

func (x *GetPipelinesRequest) Reset() {
	*x = GetPipelinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_pipelines_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelinesRequest) ProtoMessage() {}

func (x *GetPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pipelines_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelinesRequest.ProtoReflect.Descriptor instead.
func (*GetPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pipelines_proto_rawDescGZIP(), []int{1}
}

func (x *GetPipelinesRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

type GetPipelinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipelines []*Pipelines `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
}

func (x *GetPipelinesResponse) Reset() {
	*x = GetPipelinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_pipelines_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelinesResponse) ProtoMessage() {}

func (x *GetPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pipelines_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelinesResponse.ProtoReflect.Descriptor instead.
func (*GetPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pipelines_proto_rawDescGZIP(), []int{2}
}

func (x *GetPipelinesResponse) GetPipelines() []*Pipelines {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

var File_pkg_proto_pipelines_proto protoreflect.FileDescriptor

var file_pkg_proto_pipelines_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x52, 0x09, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x32, 0x64,
	0x0a, 0x0f, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x12, 0x1e, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_pipelines_proto_rawDescOnce sync.Once
	file_pkg_proto_pipelines_proto_rawDescData = file_pkg_proto_pipelines_proto_rawDesc
)

func file_pkg_proto_pipelines_proto_rawDescGZIP() []byte {
	file_pkg_proto_pipelines_proto_rawDescOnce.Do(func() {
		file_pkg_proto_pipelines_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_pipelines_proto_rawDescData)
	})
	return file_pkg_proto_pipelines_proto_rawDescData
}

var file_pkg_proto_pipelines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_pipelines_proto_goTypes = []interface{}{
	(*Pipelines)(nil),            // 0: pipelines.Pipelines
	(*GetPipelinesRequest)(nil),  // 1: pipelines.GetPipelinesRequest
	(*GetPipelinesResponse)(nil), // 2: pipelines.GetPipelinesResponse
}
var file_pkg_proto_pipelines_proto_depIdxs = []int32{
	0, // 0: pipelines.GetPipelinesResponse.pipelines:type_name -> pipelines.Pipelines
	1, // 1: pipelines.PipelineService.GetPipelines:input_type -> pipelines.GetPipelinesRequest
	2, // 2: pipelines.PipelineService.GetPipelines:output_type -> pipelines.GetPipelinesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_pipelines_proto_init() }
func file_pkg_proto_pipelines_proto_init() {
	if File_pkg_proto_pipelines_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_pipelines_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pipelines); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_pipelines_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPipelinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_pipelines_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPipelinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_pipelines_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_pipelines_proto_goTypes,
		DependencyIndexes: file_pkg_proto_pipelines_proto_depIdxs,
		MessageInfos:      file_pkg_proto_pipelines_proto_msgTypes,
	}.Build()
	File_pkg_proto_pipelines_proto = out.File
	file_pkg_proto_pipelines_proto_rawDesc = nil
	file_pkg_proto_pipelines_proto_goTypes = nil
	file_pkg_proto_pipelines_proto_depIdxs = nil
}
